### ISSUE TITLE
How to replicate worker processes

### ISSUE THREAD

**Issue by OliverFaust** [runefriborg/pycsp#31]
Hi, 
Is there a way to make the code below more elegant?
As it stands, the number of dl processes is static. I am interested to make the number of dl processes variable.

Oliver

```
import sys
from pycsp.parallel import *

@process
def source(chan_out):
    cout0 = chan_out[0].writer()
    cout1 = chan_out[1].writer()
    cout2 = chan_out[2].writer()
    cout3 = chan_out[3].writer()
    cout4 = chan_out[4].writer()
    for i in range(10):
        cout0(i+0)
        cout1(i+100)
        cout2(i+200)
        cout3(i+300)
        cout4(i+400)
    retire(cout0)
    retire(cout1)
    retire(cout2)
    retire(cout3)
    retire(cout4)

@process
def dl(chan_in, chan_out):
    while True:
        chan_out(chan_in())

@process
def sink(chan_in):
    cin0 = chan_in[0].reader()
    cin1 = chan_in[1].reader()
    cin2 = chan_in[2].reader()
    cin3 = chan_in[3].reader()
    cin4 = chan_in[4].reader()
    while True:
        print(str(cin0()))
        print(str(cin1()))
        print(str(cin2()))
        print(str(cin3()))
        print(str(cin4()))

rrVec = Channel(buffer=4)*5
res = Channel(buffer=4)*5
Parallel(
    source(rrVec),
    dl(+rrVec[0], -res[0]),
    dl(+rrVec[1], -res[1]),
    dl(+rrVec[2], -res[2]),
    dl(+rrVec[3], -res[3]),
    dl(+rrVec[4], -res[4]),
    sink(res)
)

shutdown()
```

**Comment by vinter** [comment]
Sure:) You just use Pythons own replicators:
import sys
from pycsp.parallel import *

@process
def source(chan_out):
    cout = [x.writer() for x in chan_out]
    for i in range(10):
        for c, v in zip(cout, [0, 100, 200, 300, 400]):
            c( i + v )
    for c in cout:
        retire(c)

@process
def dl(chan_in, chan_out):
    while True:
        chan_out(chan_in())

@process
def sink(chan_in):
    cin = [c.reader() for c in chan_in]
    while True:
        for c in cin:
            print(str(c()))

rrVec = Channel(buffer=4)*5
res = Channel(buffer=4)*5

Parallel(
    source(rrVec),
    [dl( +s, -d) for s,d in zip(rrVec, res)],
    sink(res)
)

shutdown()

**Comment by OliverFaust** [comment]
Excellent!
