### ISSUE TITLE
Need to make the code Python 3 compatible

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runefriborg/pycsp#9]
```
Currently the PyCSP code uses Python 2 constructs that are not Python 3 
compatible.  Very few 
changes are needed to allow syntactic compatiblity, but whether that is all 
that is needed . . . 
```

Original issue reported on code.google.com by `russel.winder` on 5 Jun 2010 at 10:56

**Comment by runefriborg** [comment]
Python 3 compatibility has been added to both pycsp.parallel and pycsp.greenlet

See Commit:
https://github.com/runefriborg/pycsp/commit/602186f7d3f01d917f1f523ae71a524e7afca578
